/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTrilhasRouteImport } from './routes/_authenticated/trilhas'
import { Route as AuthenticatedTecnicasRouteImport } from './routes/_authenticated/tecnicas'
import { Route as AuthenticatedRevisarRouteImport } from './routes/_authenticated/revisar'
import { Route as AuthenticatedRecompensasRouteImport } from './routes/_authenticated/recompensas'
import { Route as AuthenticatedProdutividadeRouteImport } from './routes/_authenticated/produtividade'
import { Route as AuthenticatedPlanoRouteImport } from './routes/_authenticated/plano'
import { Route as AuthenticatedPalavrasChaveRouteImport } from './routes/_authenticated/palavras-chave'
import { Route as AuthenticatedNecessariosRouteImport } from './routes/_authenticated/necessarios'
import { Route as AuthenticatedLeitorRouteImport } from './routes/_authenticated/leitor'
import { Route as AuthenticatedIdiomasRouteImport } from './routes/_authenticated/idiomas'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedFlashcardsRouteImport } from './routes/_authenticated/flashcards'
import { Route as AuthenticatedEstudarRouteImport } from './routes/_authenticated/estudar'
import { Route as AuthenticatedEscritaRouteImport } from './routes/_authenticated/escrita'
import { Route as AuthenticatedErrosRouteImport } from './routes/_authenticated/erros'
import { Route as AuthenticatedDuvidasRouteImport } from './routes/_authenticated/duvidas'
import { Route as AuthenticatedDesafiosRouteImport } from './routes/_authenticated/desafios'
import { Route as AuthenticatedCronogramaRouteImport } from './routes/_authenticated/cronograma'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedBrasoesRouteImport } from './routes/_authenticated/brasoes'
import { Route as AuthenticatedBibliotecaRouteImport } from './routes/_authenticated/biblioteca'
import { Route as AuthenticatedAvaliacaoRouteImport } from './routes/_authenticated/avaliacao'
import { Route as AuthenticatedAtrasadoRouteImport } from './routes/_authenticated/atrasado'
import { Route as AuthenticatedAnotacoesRouteImport } from './routes/_authenticated/anotacoes'
import { Route as AuthenticatedTrilhaContentIdRouteImport } from './routes/_authenticated/trilha.$contentId'
import { Route as AuthenticatedMaterialIdRouteImport } from './routes/_authenticated/material.$id'
import { Route as AuthenticatedAtrasadoLateIdRouteImport } from './routes/_authenticated/atrasado.$lateId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrilhasRoute = AuthenticatedTrilhasRouteImport.update({
  id: '/trilhas',
  path: '/trilhas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTecnicasRoute = AuthenticatedTecnicasRouteImport.update({
  id: '/tecnicas',
  path: '/tecnicas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevisarRoute = AuthenticatedRevisarRouteImport.update({
  id: '/revisar',
  path: '/revisar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecompensasRoute =
  AuthenticatedRecompensasRouteImport.update({
    id: '/recompensas',
    path: '/recompensas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProdutividadeRoute =
  AuthenticatedProdutividadeRouteImport.update({
    id: '/produtividade',
    path: '/produtividade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanoRoute = AuthenticatedPlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPalavrasChaveRoute =
  AuthenticatedPalavrasChaveRouteImport.update({
    id: '/palavras-chave',
    path: '/palavras-chave',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNecessariosRoute =
  AuthenticatedNecessariosRouteImport.update({
    id: '/necessarios',
    path: '/necessarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeitorRoute = AuthenticatedLeitorRouteImport.update({
  id: '/leitor',
  path: '/leitor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIdiomasRoute = AuthenticatedIdiomasRouteImport.update({
  id: '/idiomas',
  path: '/idiomas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFlashcardsRoute = AuthenticatedFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstudarRoute = AuthenticatedEstudarRouteImport.update({
  id: '/estudar',
  path: '/estudar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEscritaRoute = AuthenticatedEscritaRouteImport.update({
  id: '/escrita',
  path: '/escrita',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErrosRoute = AuthenticatedErrosRouteImport.update({
  id: '/erros',
  path: '/erros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDuvidasRoute = AuthenticatedDuvidasRouteImport.update({
  id: '/duvidas',
  path: '/duvidas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesafiosRoute = AuthenticatedDesafiosRouteImport.update({
  id: '/desafios',
  path: '/desafios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCronogramaRoute = AuthenticatedCronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrasoesRoute = AuthenticatedBrasoesRouteImport.update({
  id: '/brasoes',
  path: '/brasoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBibliotecaRoute = AuthenticatedBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvaliacaoRoute = AuthenticatedAvaliacaoRouteImport.update({
  id: '/avaliacao',
  path: '/avaliacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtrasadoRoute = AuthenticatedAtrasadoRouteImport.update({
  id: '/atrasado',
  path: '/atrasado',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnotacoesRoute = AuthenticatedAnotacoesRouteImport.update({
  id: '/anotacoes',
  path: '/anotacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrilhaContentIdRoute =
  AuthenticatedTrilhaContentIdRouteImport.update({
    id: '/trilha/$contentId',
    path: '/trilha/$contentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaterialIdRoute = AuthenticatedMaterialIdRouteImport.update({
  id: '/material/$id',
  path: '/material/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtrasadoLateIdRoute =
  AuthenticatedAtrasadoLateIdRouteImport.update({
    id: '/$lateId',
    path: '/$lateId',
    getParentRoute: () => AuthenticatedAtrasadoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/anotacoes': typeof AuthenticatedAnotacoesRoute
  '/atrasado': typeof AuthenticatedAtrasadoRouteWithChildren
  '/avaliacao': typeof AuthenticatedAvaliacaoRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/brasoes': typeof AuthenticatedBrasoesRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/cronograma': typeof AuthenticatedCronogramaRoute
  '/desafios': typeof AuthenticatedDesafiosRoute
  '/duvidas': typeof AuthenticatedDuvidasRoute
  '/erros': typeof AuthenticatedErrosRoute
  '/escrita': typeof AuthenticatedEscritaRoute
  '/estudar': typeof AuthenticatedEstudarRoute
  '/flashcards': typeof AuthenticatedFlashcardsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/idiomas': typeof AuthenticatedIdiomasRoute
  '/leitor': typeof AuthenticatedLeitorRoute
  '/necessarios': typeof AuthenticatedNecessariosRoute
  '/palavras-chave': typeof AuthenticatedPalavrasChaveRoute
  '/plano': typeof AuthenticatedPlanoRoute
  '/produtividade': typeof AuthenticatedProdutividadeRoute
  '/recompensas': typeof AuthenticatedRecompensasRoute
  '/revisar': typeof AuthenticatedRevisarRoute
  '/tecnicas': typeof AuthenticatedTecnicasRoute
  '/trilhas': typeof AuthenticatedTrilhasRoute
  '/atrasado/$lateId': typeof AuthenticatedAtrasadoLateIdRoute
  '/material/$id': typeof AuthenticatedMaterialIdRoute
  '/trilha/$contentId': typeof AuthenticatedTrilhaContentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/anotacoes': typeof AuthenticatedAnotacoesRoute
  '/atrasado': typeof AuthenticatedAtrasadoRouteWithChildren
  '/avaliacao': typeof AuthenticatedAvaliacaoRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/brasoes': typeof AuthenticatedBrasoesRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/cronograma': typeof AuthenticatedCronogramaRoute
  '/desafios': typeof AuthenticatedDesafiosRoute
  '/duvidas': typeof AuthenticatedDuvidasRoute
  '/erros': typeof AuthenticatedErrosRoute
  '/escrita': typeof AuthenticatedEscritaRoute
  '/estudar': typeof AuthenticatedEstudarRoute
  '/flashcards': typeof AuthenticatedFlashcardsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/idiomas': typeof AuthenticatedIdiomasRoute
  '/leitor': typeof AuthenticatedLeitorRoute
  '/necessarios': typeof AuthenticatedNecessariosRoute
  '/palavras-chave': typeof AuthenticatedPalavrasChaveRoute
  '/plano': typeof AuthenticatedPlanoRoute
  '/produtividade': typeof AuthenticatedProdutividadeRoute
  '/recompensas': typeof AuthenticatedRecompensasRoute
  '/revisar': typeof AuthenticatedRevisarRoute
  '/tecnicas': typeof AuthenticatedTecnicasRoute
  '/trilhas': typeof AuthenticatedTrilhasRoute
  '/atrasado/$lateId': typeof AuthenticatedAtrasadoLateIdRoute
  '/material/$id': typeof AuthenticatedMaterialIdRoute
  '/trilha/$contentId': typeof AuthenticatedTrilhaContentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/anotacoes': typeof AuthenticatedAnotacoesRoute
  '/_authenticated/atrasado': typeof AuthenticatedAtrasadoRouteWithChildren
  '/_authenticated/avaliacao': typeof AuthenticatedAvaliacaoRoute
  '/_authenticated/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/_authenticated/brasoes': typeof AuthenticatedBrasoesRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/cronograma': typeof AuthenticatedCronogramaRoute
  '/_authenticated/desafios': typeof AuthenticatedDesafiosRoute
  '/_authenticated/duvidas': typeof AuthenticatedDuvidasRoute
  '/_authenticated/erros': typeof AuthenticatedErrosRoute
  '/_authenticated/escrita': typeof AuthenticatedEscritaRoute
  '/_authenticated/estudar': typeof AuthenticatedEstudarRoute
  '/_authenticated/flashcards': typeof AuthenticatedFlashcardsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/idiomas': typeof AuthenticatedIdiomasRoute
  '/_authenticated/leitor': typeof AuthenticatedLeitorRoute
  '/_authenticated/necessarios': typeof AuthenticatedNecessariosRoute
  '/_authenticated/palavras-chave': typeof AuthenticatedPalavrasChaveRoute
  '/_authenticated/plano': typeof AuthenticatedPlanoRoute
  '/_authenticated/produtividade': typeof AuthenticatedProdutividadeRoute
  '/_authenticated/recompensas': typeof AuthenticatedRecompensasRoute
  '/_authenticated/revisar': typeof AuthenticatedRevisarRoute
  '/_authenticated/tecnicas': typeof AuthenticatedTecnicasRoute
  '/_authenticated/trilhas': typeof AuthenticatedTrilhasRoute
  '/_authenticated/atrasado/$lateId': typeof AuthenticatedAtrasadoLateIdRoute
  '/_authenticated/material/$id': typeof AuthenticatedMaterialIdRoute
  '/_authenticated/trilha/$contentId': typeof AuthenticatedTrilhaContentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/anotacoes'
    | '/atrasado'
    | '/avaliacao'
    | '/biblioteca'
    | '/brasoes'
    | '/calendario'
    | '/cronograma'
    | '/desafios'
    | '/duvidas'
    | '/erros'
    | '/escrita'
    | '/estudar'
    | '/flashcards'
    | '/home'
    | '/idiomas'
    | '/leitor'
    | '/necessarios'
    | '/palavras-chave'
    | '/plano'
    | '/produtividade'
    | '/recompensas'
    | '/revisar'
    | '/tecnicas'
    | '/trilhas'
    | '/atrasado/$lateId'
    | '/material/$id'
    | '/trilha/$contentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/anotacoes'
    | '/atrasado'
    | '/avaliacao'
    | '/biblioteca'
    | '/brasoes'
    | '/calendario'
    | '/cronograma'
    | '/desafios'
    | '/duvidas'
    | '/erros'
    | '/escrita'
    | '/estudar'
    | '/flashcards'
    | '/home'
    | '/idiomas'
    | '/leitor'
    | '/necessarios'
    | '/palavras-chave'
    | '/plano'
    | '/produtividade'
    | '/recompensas'
    | '/revisar'
    | '/tecnicas'
    | '/trilhas'
    | '/atrasado/$lateId'
    | '/material/$id'
    | '/trilha/$contentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/anotacoes'
    | '/_authenticated/atrasado'
    | '/_authenticated/avaliacao'
    | '/_authenticated/biblioteca'
    | '/_authenticated/brasoes'
    | '/_authenticated/calendario'
    | '/_authenticated/cronograma'
    | '/_authenticated/desafios'
    | '/_authenticated/duvidas'
    | '/_authenticated/erros'
    | '/_authenticated/escrita'
    | '/_authenticated/estudar'
    | '/_authenticated/flashcards'
    | '/_authenticated/home'
    | '/_authenticated/idiomas'
    | '/_authenticated/leitor'
    | '/_authenticated/necessarios'
    | '/_authenticated/palavras-chave'
    | '/_authenticated/plano'
    | '/_authenticated/produtividade'
    | '/_authenticated/recompensas'
    | '/_authenticated/revisar'
    | '/_authenticated/tecnicas'
    | '/_authenticated/trilhas'
    | '/_authenticated/atrasado/$lateId'
    | '/_authenticated/material/$id'
    | '/_authenticated/trilha/$contentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trilhas': {
      id: '/_authenticated/trilhas'
      path: '/trilhas'
      fullPath: '/trilhas'
      preLoaderRoute: typeof AuthenticatedTrilhasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tecnicas': {
      id: '/_authenticated/tecnicas'
      path: '/tecnicas'
      fullPath: '/tecnicas'
      preLoaderRoute: typeof AuthenticatedTecnicasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revisar': {
      id: '/_authenticated/revisar'
      path: '/revisar'
      fullPath: '/revisar'
      preLoaderRoute: typeof AuthenticatedRevisarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recompensas': {
      id: '/_authenticated/recompensas'
      path: '/recompensas'
      fullPath: '/recompensas'
      preLoaderRoute: typeof AuthenticatedRecompensasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtividade': {
      id: '/_authenticated/produtividade'
      path: '/produtividade'
      fullPath: '/produtividade'
      preLoaderRoute: typeof AuthenticatedProdutividadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plano': {
      id: '/_authenticated/plano'
      path: '/plano'
      fullPath: '/plano'
      preLoaderRoute: typeof AuthenticatedPlanoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/palavras-chave': {
      id: '/_authenticated/palavras-chave'
      path: '/palavras-chave'
      fullPath: '/palavras-chave'
      preLoaderRoute: typeof AuthenticatedPalavrasChaveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/necessarios': {
      id: '/_authenticated/necessarios'
      path: '/necessarios'
      fullPath: '/necessarios'
      preLoaderRoute: typeof AuthenticatedNecessariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leitor': {
      id: '/_authenticated/leitor'
      path: '/leitor'
      fullPath: '/leitor'
      preLoaderRoute: typeof AuthenticatedLeitorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/idiomas': {
      id: '/_authenticated/idiomas'
      path: '/idiomas'
      fullPath: '/idiomas'
      preLoaderRoute: typeof AuthenticatedIdiomasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flashcards': {
      id: '/_authenticated/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof AuthenticatedFlashcardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estudar': {
      id: '/_authenticated/estudar'
      path: '/estudar'
      fullPath: '/estudar'
      preLoaderRoute: typeof AuthenticatedEstudarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escrita': {
      id: '/_authenticated/escrita'
      path: '/escrita'
      fullPath: '/escrita'
      preLoaderRoute: typeof AuthenticatedEscritaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/erros': {
      id: '/_authenticated/erros'
      path: '/erros'
      fullPath: '/erros'
      preLoaderRoute: typeof AuthenticatedErrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/duvidas': {
      id: '/_authenticated/duvidas'
      path: '/duvidas'
      fullPath: '/duvidas'
      preLoaderRoute: typeof AuthenticatedDuvidasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desafios': {
      id: '/_authenticated/desafios'
      path: '/desafios'
      fullPath: '/desafios'
      preLoaderRoute: typeof AuthenticatedDesafiosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cronograma': {
      id: '/_authenticated/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof AuthenticatedCronogramaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brasoes': {
      id: '/_authenticated/brasoes'
      path: '/brasoes'
      fullPath: '/brasoes'
      preLoaderRoute: typeof AuthenticatedBrasoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblioteca': {
      id: '/_authenticated/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AuthenticatedBibliotecaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avaliacao': {
      id: '/_authenticated/avaliacao'
      path: '/avaliacao'
      fullPath: '/avaliacao'
      preLoaderRoute: typeof AuthenticatedAvaliacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atrasado': {
      id: '/_authenticated/atrasado'
      path: '/atrasado'
      fullPath: '/atrasado'
      preLoaderRoute: typeof AuthenticatedAtrasadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anotacoes': {
      id: '/_authenticated/anotacoes'
      path: '/anotacoes'
      fullPath: '/anotacoes'
      preLoaderRoute: typeof AuthenticatedAnotacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trilha/$contentId': {
      id: '/_authenticated/trilha/$contentId'
      path: '/trilha/$contentId'
      fullPath: '/trilha/$contentId'
      preLoaderRoute: typeof AuthenticatedTrilhaContentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/material/$id': {
      id: '/_authenticated/material/$id'
      path: '/material/$id'
      fullPath: '/material/$id'
      preLoaderRoute: typeof AuthenticatedMaterialIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atrasado/$lateId': {
      id: '/_authenticated/atrasado/$lateId'
      path: '/$lateId'
      fullPath: '/atrasado/$lateId'
      preLoaderRoute: typeof AuthenticatedAtrasadoLateIdRouteImport
      parentRoute: typeof AuthenticatedAtrasadoRoute
    }
  }
}

interface AuthenticatedAtrasadoRouteChildren {
  AuthenticatedAtrasadoLateIdRoute: typeof AuthenticatedAtrasadoLateIdRoute
}

const AuthenticatedAtrasadoRouteChildren: AuthenticatedAtrasadoRouteChildren = {
  AuthenticatedAtrasadoLateIdRoute: AuthenticatedAtrasadoLateIdRoute,
}

const AuthenticatedAtrasadoRouteWithChildren =
  AuthenticatedAtrasadoRoute._addFileChildren(
    AuthenticatedAtrasadoRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnotacoesRoute: typeof AuthenticatedAnotacoesRoute
  AuthenticatedAtrasadoRoute: typeof AuthenticatedAtrasadoRouteWithChildren
  AuthenticatedAvaliacaoRoute: typeof AuthenticatedAvaliacaoRoute
  AuthenticatedBibliotecaRoute: typeof AuthenticatedBibliotecaRoute
  AuthenticatedBrasoesRoute: typeof AuthenticatedBrasoesRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedCronogramaRoute: typeof AuthenticatedCronogramaRoute
  AuthenticatedDesafiosRoute: typeof AuthenticatedDesafiosRoute
  AuthenticatedDuvidasRoute: typeof AuthenticatedDuvidasRoute
  AuthenticatedErrosRoute: typeof AuthenticatedErrosRoute
  AuthenticatedEscritaRoute: typeof AuthenticatedEscritaRoute
  AuthenticatedEstudarRoute: typeof AuthenticatedEstudarRoute
  AuthenticatedFlashcardsRoute: typeof AuthenticatedFlashcardsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedIdiomasRoute: typeof AuthenticatedIdiomasRoute
  AuthenticatedLeitorRoute: typeof AuthenticatedLeitorRoute
  AuthenticatedNecessariosRoute: typeof AuthenticatedNecessariosRoute
  AuthenticatedPalavrasChaveRoute: typeof AuthenticatedPalavrasChaveRoute
  AuthenticatedPlanoRoute: typeof AuthenticatedPlanoRoute
  AuthenticatedProdutividadeRoute: typeof AuthenticatedProdutividadeRoute
  AuthenticatedRecompensasRoute: typeof AuthenticatedRecompensasRoute
  AuthenticatedRevisarRoute: typeof AuthenticatedRevisarRoute
  AuthenticatedTecnicasRoute: typeof AuthenticatedTecnicasRoute
  AuthenticatedTrilhasRoute: typeof AuthenticatedTrilhasRoute
  AuthenticatedMaterialIdRoute: typeof AuthenticatedMaterialIdRoute
  AuthenticatedTrilhaContentIdRoute: typeof AuthenticatedTrilhaContentIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnotacoesRoute: AuthenticatedAnotacoesRoute,
  AuthenticatedAtrasadoRoute: AuthenticatedAtrasadoRouteWithChildren,
  AuthenticatedAvaliacaoRoute: AuthenticatedAvaliacaoRoute,
  AuthenticatedBibliotecaRoute: AuthenticatedBibliotecaRoute,
  AuthenticatedBrasoesRoute: AuthenticatedBrasoesRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedCronogramaRoute: AuthenticatedCronogramaRoute,
  AuthenticatedDesafiosRoute: AuthenticatedDesafiosRoute,
  AuthenticatedDuvidasRoute: AuthenticatedDuvidasRoute,
  AuthenticatedErrosRoute: AuthenticatedErrosRoute,
  AuthenticatedEscritaRoute: AuthenticatedEscritaRoute,
  AuthenticatedEstudarRoute: AuthenticatedEstudarRoute,
  AuthenticatedFlashcardsRoute: AuthenticatedFlashcardsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedIdiomasRoute: AuthenticatedIdiomasRoute,
  AuthenticatedLeitorRoute: AuthenticatedLeitorRoute,
  AuthenticatedNecessariosRoute: AuthenticatedNecessariosRoute,
  AuthenticatedPalavrasChaveRoute: AuthenticatedPalavrasChaveRoute,
  AuthenticatedPlanoRoute: AuthenticatedPlanoRoute,
  AuthenticatedProdutividadeRoute: AuthenticatedProdutividadeRoute,
  AuthenticatedRecompensasRoute: AuthenticatedRecompensasRoute,
  AuthenticatedRevisarRoute: AuthenticatedRevisarRoute,
  AuthenticatedTecnicasRoute: AuthenticatedTecnicasRoute,
  AuthenticatedTrilhasRoute: AuthenticatedTrilhasRoute,
  AuthenticatedMaterialIdRoute: AuthenticatedMaterialIdRoute,
  AuthenticatedTrilhaContentIdRoute: AuthenticatedTrilhaContentIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
